/*
 * Copyright 2019 JF James.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.sebjef.easypay.boundary;

import java.util.Optional;
import org.sebjef.easypay.entity.PaymentResponseCode;
import org.sebjef.easypay.entity.CardType;
import org.sebjef.easypay.entity.ProcessingMode;

/**
 *
 * @author JF James
 */

public class PaymentResponse {

    // Data coming from the request
    private String posId;
    private String cardNumber;
    private String expiryDate;
    private int amount;

    // Data generated by the processing
    private long paymentId;
    private PaymentResponseCode responseCode;
    private Optional<Long> authorId;
    private CardType cardType;
    private boolean bankCalled;
    private boolean authorized;
    private long responseTime;
    private ProcessingMode processingMode;

    public long getPaymentId() {
        return paymentId;
    }

    public void setPaymentId(long paymentId) {
        this.paymentId = paymentId;
    }

    public String getPosId() {
        return posId;
    }

    public void setPosId(String posId) {
        this.posId = posId;
    }

    public String getCardNumber() {
        return cardNumber;
    }

    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    public String getExpiryDate() {
        return expiryDate;
    }

    public void setExpiryDate(String expiryDate) {
        this.expiryDate = expiryDate;
    }

    public int getAmount() {
        return amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    public PaymentResponseCode getResponseCode() {
        return responseCode;
    }

    public void setResponseCode(PaymentResponseCode responseCode) {
        this.responseCode = responseCode;
    }

    public Optional<Long> getAuthorId() {
        return authorId;
    }

    public void setAuthorId(Optional<Long> authorId) {
        this.authorId = authorId;
    }

    public CardType getCardType() {
        return cardType;
    }

    public void setCardType(CardType cardType) {
        this.cardType = cardType;
    }

    public boolean isBankCalled() {
        return bankCalled;
    }

    public void setBankCalled(boolean bankCalled) {
        this.bankCalled = bankCalled;
    }

    public boolean isAuthorized() {
        return authorized;
    }

    public void setAuthorized(boolean authorized) {
        this.authorized = authorized;
    }

    public long getResponseTime() {
        return responseTime;
    }

    public void setResponseTime(long responseTime) {
        this.responseTime = responseTime;
    }

    public ProcessingMode getProcessingMode() {
        return processingMode;
    }

    public void setProcessingMode(ProcessingMode processingMode) {
        this.processingMode = processingMode;
    }
}
